name: IronElevatorYwY
version: '${project.version}'
main: net.torosamy.ironelevatorywy.IronElevatorYwY
api-version: '1.20'
authors: [yweiyang]
softdepend:
  - PlaceholderAPI
commands:
  ieywy:
    usage: /ieywy reload
    permission: ironelevatorywy.reload
permissions:
  ironelevatorywy.use:
    default: true
    description: "if player can use this plugin"
  ironelevatorywy.reload:
    default: op
    description: "use to reload this plugin config"